---
name: 'Apps-Garage HUD - Demo Config'

server:
  port: 8080

contactGroups:
  - name: 'Applications'
    contacts: [
      { name: 'Riley', ext: '0101'},
      { name: 'OtherPerson', ext: '0102'},
    ]
  - name: 'Field Services'
    contacts: [
      {name: 'AnotherPer', ext: '1010'},
      {name: 'RamJam', ext: '1011'},
    ]
  - name: 'Server'
    contacts: [
      {name: 'Demo Uno', ext: '0103'},
      {name: 'Demo Dos', ext: '0104'},
    ]
  - name: 'Networking'
    contacts: [
      {name: 'Too Many', ext: '0105'},
      {name: 'Json is Cool', ext: '0106'},
    ]
  - name: 'Security'
    contacts: [
      {name: 'Contact 4', ext: '0107'},
      {name: 'Contact 5 ', ext: '0000'},
    ]

